#https://blog-ja.sideci.com/entry/2015/03/26/103000参考
Rails:
  Enabled: true

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.3.1
  # 除外するファイル
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - "Guardfile"
    - "Gemfile"
    - "spec/spec_helper.rb"
Style/WhileUntilModifier:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Layout/CaseIndentation:
  EnforcedStyle: end
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 30
  Exclude:
    - "spec/**/*"
Naming/AccessorMethodName:
  Enabled: false

Layout/AlignArray:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/AlignParameters:
  EnforcedStyle: with_first_parameter

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces
Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/FormatStringToken:
  Enabled: false